### ISSUE TITLE
broke my discord

### ISSUE THREAD

**Issue by hiilikewiki** [cemahseri/DiscordCrasherVideoGenerator#1]
hi,
I used this, uploaded a video, checked it and my discord crashed...... how can I fix this?

**Comment by cemahseri** [comment]
Hello,

It's too sad that you've tested this crasher video generator and it's crashed your Discord. You̵ c̵an̶ _t̶ry_ t̵o **c̴l̵o̵s̵e̴** y̶ou̸r̶ ̵**D̶i̸sc̴or̶d̴** f̵̰̖͛̎r̵̨̛̤o̷͙̔͘m̶̱̖̔̕ _T̴̛̏a̵̠̼̽̉s̴͉͘k̴͛̚_ ̵͊**M̵̂̾a̵̓͊n̴͐̇ã̷̽g̸ë̸̘́̆ř̷ͅ** â̵̪n̷̡͘d̴̖̓ **ǹ̴̡͉̘͈͠O̶̺̓͜ NO̵̼̺̪͎͌̓͝O NOÔ̶̰̜̼̫̌̎͘O̷̻̣̻̼̍̅OÖ̷̤͇͔́̓̈͝** _it̵'s too la̷te_  ̶͋̆̏̐̕ ̶̈̊̌͑̚ ̷̎ ̷̓̽̿̈́͒   ̷̛͆̍̅̒̅͛̌̂́̕͝ ̴́ ̵̜̫̬̄̍͋̌̕͘͘͝ ̶̇̊ ̷̡̛̱̩̲͔̳̠̮͈̝͉̟̋̂̓̅̃͐̋͠
­
­
­
­
­
­

Y̵̡̢̘͕͙̰̞̝̙͇̺͍͖̰̥̐̑̅͋͌͜ͅƠ̶͎̈́̐̆̎̃̌̓̐͛̃̕͝Ư̶̩̘̪̣͖̞͔̮̹̗̖̖̖̱̰̾͒̓͛͌̐̿̍͊́͛̔̄͘̕̕͘̕ _H̷̗́̾͌͘͘͜A̷̧̼͈̥̱̻̰͇͚͙̥͕̜̮̰͈̼͙̓̎̈́̔̈́̒̚V̷̫̲̀̋̇̔̈Ę̸̲̬̗̮̪̝̩̳̠̈́̾̾͐͗̄͌̃̓̀̑̐̈́́̕̕͜͝ͅ_ A̸̧̛͙̘͇̗̲̻̳͍̙̮̔́̇̋̎̽͌̂͌̃̉̆̑͝Ẅ̴̻͈̻́̎́̈́̈̃̄̊̅̎͊̏̅́̿̔̈̍͌̃̐̎̍͗̾͛̎͘͜͝͠͠Ả̸̢̢̰̪̥͍̬͕͇̬͍̖̺̟̦̖̃̒̄͋͑͌͐̑͗̃̐́̅͗̌̽̑̓̏̀́̋͂̋͘͜Ķ̴̯̭̦̫͍̰̜̖̗̼̫͈̖̣̥̳̖͙̫̜͔̖͔̯̳̭̉̀̋͛̾͆̎͂͂̊̎͊̀̒É̸̟̟͓̈́͑͊̓́̓̀͒̇͋̓͂̅͋̑͋̿̈͆̐̐̃͒̔͠N̵̡̤̙͕̉̀̊͑̎ T̵̢̤̜̩̜̬̳̰̫̲̩̜̲͓̹̮̥̏̀͌̃͜ͅH̴̡̢̧̘̳̤̳̘̻̟̠̱̲͚̝̼̹̬͇̜̜̪̫͕̦̮͖̺͎̱̫̬̋̈́̀̃̂̇̇́͊́̃͐͊̎̀͛͊̊͛͊͂͂̀̇̈́͐̍̓̎͗̕̕̕͜͜ͅͅȄ̴̮͇̭͖̱̻̬̲̠̖̏̈ **C̶̛͓͇̺̜̱̲̥̥͎̯͕͉̠̭̐͌̈̓͋̇̈́͆̓̅͆̈́̑͊̇̇̅́̔͗̆̈̆̄̾̈́́͐͌̑̃̽̄͊͂̂̈́͘̕͘̕͠͝͝T̶̞͎͖̝̺̣̳̓͒̆͒̓͗͐̾͗͐̿̐̊̿͐̆̈̒͋̓̓̊̌͂̄̾͒̊̾̃̚͝͝͠͝͠͠H̷̨̧̨̨̧̡̡͖̣̻̼͕̩̱͇͈͕̖̰̪͔͖͎̱̻̫̯͕̬̙̗̼̲̥̤͙͖̟͕̱͚̯͈͖̬̪͕̻̭̣̬̦͖̳̘̜̯̟͍͇̦̦͙̳̜̣̗͕͈͈͕̭̠͙̫͒̆̾̈́̆́̆̿̌͆̈̈́͛̚͜͜͠ͅU̷̼̪̫̥̍̀͗̇̊̓͌̆̄̊́͒̆͒̽͂̊͋̓̾͆̈̈̑́̔̔̀̿̉̔̓͒̑̓̓̅́͑̃͆̅͂̕͠͝͠͝͝͝Ļ̵̨̢̨̡̨̡̛̛̛̦̳̗̰̲̭͍̗͚͓̲̘̲̭̞̪͇̼̼͕̬̖͙̺̘̰̹̩̮̹̞͎̹̠͔̥̭̝̤̱̭̺̮͈͍̥̯̰̦̯̹̹̙̪̟̘̜͎̭̻̦̠̙̪͎͍̏̉́͌͆̇͋̊̈́̔͋͐̓̂̔̒̔̏̎͂͆͂̐̈́̅̿̏̍̈̂̃̄̇̈́̑̍͛̉͋̓͒̂̌͌̑̀͗̌͆̾̽͑͋̚͘̕͘͘̕̚̚͠͝͠͝͝͝H̸̢̡̛̦̰͎̭̤͇̲͎̮̟̝̣̤͐͆͛̃́́̄̇̂͋̇̎̍͋͊̍̾͋̽̂͛͌̇̈͆͂͂͗͆͑͐͗̀́́͊͆̀͋̎͌̒̆̓̉̑́̏̔̀̑̑̾̍̀̔͋͛̽̇̔͗̉̕̕̚̕͘̚͝͠Ư̷̧̨̡̧̧̢̛̛̞̝̫̜̣̲̣̭̝̖̣̲̤̭͕̻̳̯͔̗͕͔̺͙̮͉̞̞̞̼͕̹̳͖̮̰̦͔̥̠̫̮̻͕̫̦̙͎̹͈͓̬̱̹̪̥̠̹̗̟͇̻̲̰̯͚̊͆̉̏̑͊̑́̄̀͗͂̉̈́̈́́̈́̓̋̀̽͐̔̾̈́̅͋̒͆̌̌̌̐̏̒͌̽͌͊͑̿̓̍̕̚̕̕͘͜͠͠͝͠ͅͅ**

**Comment by hiilikewiki** [comment]
I think its on your end.

**Comment by rube200** [comment]
Stupid dev, cant fix a simple issue
<3
