### ISSUE TITLE
The system cannot find the file specified.

### ISSUE THREAD

**Issue by RusstyCrussty123** [cemahseri/DiscordCrasherVideoGenerator#4]
![image](https://user-images.githubusercontent.com/61127918/114134345-32077800-98cd-11eb-8f81-6f2477f7e6ee.png)

I don't understand.

**Comment by cemahseri** [comment]
Hey, hello!

Please be sure that `ffmpeg.exe` exists on the same directory with `DiscordCrasherVideoGenerator.exe`. If it exists, please name your video file to something like `test.mp4`, as I've stated in the README.md;
> Also, be sure that the file's name is full of alphanumeric letters. Don't put any space, special character, number, etc.

Let me know if it works.

**Comment by RusstyCrussty123** [comment]
So I did everything you said. Now it makes an mp4 file with _crasher at the end but it doesn't crash discord.

**Comment by cemahseri** [comment]
Honestly I do not know what causes that. Some people *(including me)* can get it working, but it doesn't work on some people. I've tested with few of my friends but it didn't worked on all of theirs PC. I will be updating this program with a much more great one. I am just busy nowadays. But be sure that I will update this repo. Thanks for helping me out to find out the problems!

**Comment by cemahseri** [comment]
Hey! I've finally updated the application. Sorry for the delay. Enjoy!
