### ISSUE TITLE
Explanation of how this works please?

### ISSUE THREAD

**Issue by s-alad** [cemahseri/DiscordCrasherVideoGenerator#6]
Could you explain your method of making this corrupted video, thanks!

**Comment by cemahseri** [comment]
Just download the release, unarchive it, and drag & drop your video onto the executable file. I recommend you to take a look at the README.md file before using the program.

**Comment by s-alad** [comment]
I meant like what the code does to the mp4 to corrupt it

**Comment by cemahseri** [comment]
Oh, sorry. You meant that... Well, just concatenate the original video and the corrupted sample. That's it. I will update the method soon and will use another different method. I will update the README.md about how it works. Thanks!

**Comment by cemahseri** [comment]
Hello there! I've updated the README.md and I thought it would be interesting for you to read. It contains more information about the crashing process. You can also check the source code. there is tons of comment lines to explain what is going on.
