### ISSUE TITLE
Youtuber took this and is profiting off of you with paid link. 

### ISSUE THREAD

**Issue by NicosHere** [cemahseri/DiscordCrasherVideoGenerator#7]
Would recommend you copy strike, they didn't even link this repo.

https://www.youtube.com/watch?v=MpriPv6bnU4

**Comment by cemahseri** [comment]
It's all okay. I've checked the video and the source code of the file. It uses a different method to create a crashed video. Anyway, thanks for reaching me out and informing me. I really appreciate that!
