### ISSUE TITLE
Did not understand what to do

### ISSUE THREAD

**Issue by NotFaizen** [cemahseri/DiscordCrasherVideoGenerator#9]
Can you please explain how to use this? I don't seem to understand. Thanks

**Comment by cemahseri** [comment]
Hello there! Well, you just have to drag-and-drop the video to the executable file, which ends with `.exe`. Currently, the program doesn't work perfectly. I will try to update it until tomorrow. So, please check back tomorrow!

**Comment by cemahseri** [comment]
Hey! I've said tomorrow but I had some urgent stuff to do, sorry about that. I've finally updated it. Enjoy!
